version: '3.8'

volumes:
  postgres_db_data:

services:
  node_app:
    container_name: 'node-app-container'
    build: .
    env_file:
      - .env
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    depends_on:
      - postgresql_db

  postgresql_db:
    image: postgres:16
    restart: always
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d/
      - postgres_db_data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      PGDATA: /var/lib/postgresql/pgdata

  run_unit_test:
    container_name: 'node-app-unit-test-container'
    build: .
    command: 'npm run test'
